from enum import StrEnum


class ProgressEvent(StrEnum):
    STARTED = "STARTED"
    AUTH_CHECK = "AUTH_CHECK"
    USER_RESOLVED = "USER_RESOLVED"
    BFS_STEP = "BFS_STEP"
    FRIENDS_LOADED = "FRIENDS_LOADED"
    PROFILE_FILTERED = "PROFILE_FILTERED"
    HUB_SKIPPED = "HUB_SKIPPED"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    FOUND = "FOUND"
    NOT_FOUND = "NOT_FOUND"
    ERROR = "ERROR"
    CANCELLED = "CANCELLED"
